require('dotenv').config()
const express = require('express')
const mongoose = require('mongoose')
const cors = require('cors')
const authRoutes = require('./routes/auth')
const projectRoutes = require('./routes/projects')
const taskRoutes = require('./routes/tasks')
const activityRoutes = require('./routes/activity')
const { errorHandler } = require('./middlewares/error')
const app = express()
app.use(cors())
app.use(express.json())
app.use('/api/auth', authRoutes)
app.use('/api/projects', projectRoutes)
app.use('/api/tasks', taskRoutes)
app.use('/api/activity', activityRoutes)
app.use(errorHandler)
const PORT = process.env.PORT || 5000
mongoose.connect(process.env.MONGO_URI).then(()=>{
  app.listen(PORT)
}).catch(err=>{
  console.error(err)
})
