require('dotenv').config()
const mongoose = require('mongoose')
const bcrypt = require('bcryptjs')
const User = require('./models/User')
const Project = require('./models/Project')
const Task = require('./models/Task')
const Activity = require('./models/Activity')
const run = async () => {
  await mongoose.connect(process.env.MONGO_URI)
  await User.deleteMany({})
  await Project.deleteMany({})
  await Task.deleteMany({})
  await Activity.deleteMany({})
  const adminPass = await bcrypt.hash('adminpass', 10)
  const memberPass = await bcrypt.hash('memberpass', 10)
  const admin = await User.create({ name: 'Admin User', email: 'admin@example.com', password: adminPass, role: 'admin' })
  const member = await User.create({ name: 'Member User', email: 'member@example.com', password: memberPass, role: 'member' })
  const project = await Project.create({ title: 'Demo Project', description: 'Demo', owner: admin._id, members: [admin._id, member._id] })
  const task1 = await Task.create({ title: 'Setup repo', project: project._id, assignee: member._id, priority: 'high', dueDate: new Date(Date.now() + 86400000) })
  const task2 = await Task.create({ title: 'Design UI', project: project._id, assignee: admin._id, priority: 'medium', dueDate: new Date(Date.now() - 86400000) })
  await Activity.create({ type: 'seed', message: 'Seeded data', user: admin._id, project: project._id })
  process.exit()
}
run()
